name: Docker App CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Login to Docker Hub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v3
      with:
        username: riswan38
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Extract metadata for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: riswan38/flask-app
        tags: |
          type=raw,value=latest,enable={{is_default_branch}}
          type=sha,format=long
          type=ref,event=branch
          type=ref,event=tag


    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Test container
      run: |
        docker run -d -p 5000:5000 --name flask-app riswan38/flask-app:${{ github.sha }}
        sleep 5
        curl --retry 3 --retry-delay 5 -s http://localhost:5000 | grep "Enter your name" || exit 1
